// Build-time tool: extracts CPU/feature tables from LLVM's MCSubtargetInfo
// and emits them as standalone C/C++ data files with no LLVM dependency.
//
// Usage: gen_target_tables <triple> > target_tables_<arch>.h
//
// This tool links against LLVM at build time, but the output files do not.

#include "llvm/Config/llvm-config.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/ADT/Twine.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/TargetParser/Host.h"
#include "llvm/TargetParser/Triple.h"
#include "llvm/Support/InitLLVM.h"
#include "llvm/Support/TargetSelect.h"
#include "llvm/Support/raw_ostream.h"

#include <algorithm>
#include <memory>
#include <string>
#include <vector>

using namespace llvm;

static std::unique_ptr<MCSubtargetInfo> getSTI(const Triple &TT) {
    std::string Error;
    const Target *TheTarget = TargetRegistry::lookupTarget(TT.str(), Error);
    if (!TheTarget) {
        errs() << "Error: " << Error << "\n";
        return nullptr;
    }
    return std::unique_ptr<MCSubtargetInfo>(
        TheTarget->createMCSubtargetInfo(TT.str(), "generic", ""));
}

// Get features for a specific CPU
static FeatureBitset getFeaturesForCPU(const Triple &TT, StringRef CPU) {
    std::string Error;
    const Target *TheTarget = TargetRegistry::lookupTarget(TT.str(), Error);
    if (!TheTarget) return {};
    auto STI = std::unique_ptr<MCSubtargetInfo>(
        TheTarget->createMCSubtargetInfo(TT.str(), CPU, ""));
    if (!STI) return {};
    return STI->getFeatureBits();
}

static void emitHeader(raw_ostream &OS, StringRef Arch) {
    OS << "// Auto-generated by gen_target_tables from LLVM's TableGen data.\n";
    OS << "// DO NOT EDIT - regenerate with: gen_target_tables <triple>\n";
    OS << "//\n";
    OS << "// Derived from LLVM Project data (Apache License v2.0 with LLVM Exceptions).\n";
    OS << "// See https://llvm.org/LICENSE.txt for details.\n";
    OS << "//\n";
    OS << "// No LLVM runtime dependency.\n\n";

    std::string Guard = "TARGET_TABLES_" + Arch.upper() + "_H";
    OS << "#ifndef " << Guard << "\n";
    OS << "#define " << Guard << "\n\n";
    OS << "#include <stdint.h>\n";
    OS << "#include <stddef.h>\n";
    OS << "#include <string.h>\n\n";
    OS << "#if defined(__GNUC__) || defined(__clang__)\n";
    OS << "#define CPUFEATURES_UNUSED __attribute__((unused))\n";
    OS << "#else\n";
    OS << "#define CPUFEATURES_UNUSED\n";
    OS << "#endif\n\n";
}

static void emitFooter(raw_ostream &OS, StringRef Arch) {
    std::string Guard = "TARGET_TABLES_" + Arch.upper() + "_H";
    OS << "#endif // " << Guard << "\n";
}

// Emit the feature bitset type
static void emitBitsetType(raw_ostream &OS, unsigned NumWords) {
    OS << "// Feature bitset: " << NumWords << " x uint64_t = "
       << (NumWords * 64) << " bits\n";
    OS << "#define TARGET_FEATURE_WORDS " << NumWords << "\n";
    OS << "#define TARGET_TABLES_LLVM_VERSION_MAJOR " << LLVM_VERSION_MAJOR << "\n";
    OS << "#define TARGET_TABLES_LLVM_VERSION_MINOR " << LLVM_VERSION_MINOR << "\n";
    OS << "#define TARGET_TABLES_LLVM_VERSION_PATCH " << LLVM_VERSION_PATCH << "\n\n";
    OS << "typedef struct {\n";
    OS << "    uint64_t bits[TARGET_FEATURE_WORDS];\n";
    OS << "} FeatureBits;\n\n";

    OS << "static inline int feature_test(const FeatureBits *fb, unsigned bit) {\n";
    OS << "    return (fb->bits[bit / 64] >> (bit % 64)) & 1;\n";
    OS << "}\n\n";

    OS << "static inline void feature_set(FeatureBits *fb, unsigned bit) {\n";
    OS << "    fb->bits[bit / 64] |= (1ULL << (bit % 64));\n";
    OS << "}\n\n";

    OS << "static inline void feature_clear(FeatureBits *fb, unsigned bit) {\n";
    OS << "    fb->bits[bit / 64] &= ~(1ULL << (bit % 64));\n";
    OS << "}\n\n";

    OS << "static inline void feature_or(FeatureBits *dst, const FeatureBits *src) {\n";
    OS << "    for (int i = 0; i < TARGET_FEATURE_WORDS; i++)\n";
    OS << "        dst->bits[i] |= src->bits[i];\n";
    OS << "}\n\n";

    OS << "static inline void feature_and(FeatureBits *dst, const FeatureBits *src) {\n";
    OS << "    for (int i = 0; i < TARGET_FEATURE_WORDS; i++)\n";
    OS << "        dst->bits[i] &= src->bits[i];\n";
    OS << "}\n\n";

    OS << "static inline void feature_andnot(FeatureBits *dst, const FeatureBits *a, const FeatureBits *b) {\n";
    OS << "    for (int i = 0; i < TARGET_FEATURE_WORDS; i++)\n";
    OS << "        dst->bits[i] = a->bits[i] & ~b->bits[i];\n";
    OS << "}\n\n";

    OS << "static inline void feature_and_out(FeatureBits *dst, const FeatureBits *a, const FeatureBits *b) {\n";
    OS << "    for (int i = 0; i < TARGET_FEATURE_WORDS; i++)\n";
    OS << "        dst->bits[i] = a->bits[i] & b->bits[i];\n";
    OS << "}\n\n";

    OS << "static inline int feature_any(const FeatureBits *fb) {\n";
    OS << "    for (int i = 0; i < TARGET_FEATURE_WORDS; i++)\n";
    OS << "        if (fb->bits[i]) return 1;\n";
    OS << "    return 0;\n";
    OS << "}\n\n";

    OS << "// Returns 1 if a and b share any set bits, 0 otherwise.\n";
    OS << "static inline int feature_intersects(const FeatureBits *a, const FeatureBits *b) {\n";
    OS << "    for (int i = 0; i < TARGET_FEATURE_WORDS; i++)\n";
    OS << "        if (a->bits[i] & b->bits[i]) return 1;\n";
    OS << "    return 0;\n";
    OS << "}\n\n";

    OS << "static inline unsigned feature_popcount(const FeatureBits *fb) {\n";
    OS << "    unsigned count = 0;\n";
    OS << "    for (int i = 0; i < TARGET_FEATURE_WORDS; i++)\n";
    OS << "        count += __builtin_popcountll(fb->bits[i]);\n";
    OS << "    return count;\n";
    OS << "}\n\n";

    OS << "static inline int feature_equal(const FeatureBits *a, const FeatureBits *b) {\n";
    OS << "    for (int i = 0; i < TARGET_FEATURE_WORDS; i++)\n";
    OS << "        if (a->bits[i] != b->bits[i]) return 0;\n";
    OS << "    return 1;\n";
    OS << "}\n\n";
}

static void emitFeatureBits(raw_ostream &OS, const FeatureBitset &Bits, unsigned NumWords) {
    OS << "{ { ";
    for (unsigned i = 0; i < NumWords; i++) {
        uint64_t Word = 0;
        for (unsigned j = 0; j < 64; j++) {
            unsigned Bit = i * 64 + j;
            if (Bit < Bits.size() && Bits.test(Bit))
                Word |= (1ULL << j);
        }
        if (i > 0) OS << ", ";
        OS << "0x" << Twine::utohexstr(Word) << "ULL";
    }
    OS << " } }";
}

static FeatureBitset computeHWMask(ArrayRef<SubtargetFeatureKV> Features,
                                    ArrayRef<SubtargetSubTypeKV> CPUs,
                                    const FeatureBitset &FeatureSetMask,
                                    const FeatureBitset &UArchMask) {
    FeatureBitset HWMask;
    FeatureBitset TuneImplied;
    for (const auto &CPU : CPUs) {
        HWMask      |= CPU.Implies.getAsBitset();
        TuneImplied |= CPU.TuneImplies.getAsBitset();
    }

    bool changed = true;
    while (changed) {
        changed = false;
        for (const auto &F : Features) {
            if (HWMask.test(F.Value)) {
                // Apply forward closure to HW bits (anything required by a HW
                // feature is a HW feature)
                FeatureBitset before = HWMask;
                HWMask |= F.Implies.getAsBitset();
                if (HWMask != before) changed = true;
            } else {
                if (TuneImplied.test(F.Value)) continue;
                if (FeatureSetMask.test(F.Value)) continue;
                if (UArchMask.test(F.Value)) continue;
                // Apply reverse closure to HW bits (anything that requires a HW
                // feature is a HW feature, except for featureset/uarch bits and
                // any 'features' implied via tuning)
                if ((F.Implies.getAsBitset() & HWMask).any()) {
                    HWMask.set(F.Value);
                    changed = true;
                }
            }
        }
    }

    // Effectively tuning flags
    HWMask &= ~UArchMask;

    return HWMask;
}

#include "llvm/TargetParser/AArch64TargetParser.h"

// Privileged features: per-arch list of feature names usable only at
// higher exception / privilege levels.
//
// These don't affect codegen for user space applications but are
// important to filter out from feature strings.

static std::vector<StringRef> getPrivilegedFeatureNamesX86() {
    return { "invpcid", "pconfig", "wbnoinvd", "hreset", "xsaves" };
}

static std::vector<StringRef> getPrivilegedFeatureNamesAArch64() {
    return {
        // Exception levels / virtualization (Arm ARM D5)
        "el2vmsa", "el3", "sel2", "vh", "hcx", "nv", "mec", "rme",
        // Non-maskable interrupts (EL2/EL3 — FEAT_NMI)
        "nmi",
        // 128-bit page-table descriptors and sysreg ISA (Arm ARM D8 — FEAT_D128)
        "d128",
        // Instrumentation extension; implies trace/ETE, EL1+ only (FEAT_ITE)
        "ite",
        // RAS v2: system-register-only, EL1+ (FEAT_RASv2)
        "rasv2",
        // EL2 trap controls (Arm ARM D13 — FEAT_FGT)
        "fgt",
        // EL1+ system registers / PSTATE bits / kernel ABI
        "pan", "pan-rwv", "uaops", "xs", "tlb-rmi",
        // Activity monitor / RAS / MPAM / PMU programming
        "am", "amvs", "mpam", "perfmon",
        // Trace / profiling (EL1+ programming registers)
        "ete", "brbe", "spe", "spe-eef", "trbe", "tracev8.4",
        // Cache identification register (CCSIDR_EL1)
        "ccidx",
    };
}

static std::vector<StringRef> getPrivilegedFeatureNamesRISCV() {
    return {
        // Hypervisor extension and the RVA23 "Augmented Hypervisor"
        "h", "sha",
        // Hypervisor-extension profile attributes (Sh*)
        "shcounterenw", "shgatpa", "shtvala",
        "shvsatpa", "shvstvala", "shvstvecd",
        // Advanced Interrupt Architecture (M and S levels)
        "smaia", "ssaia",
        // Supervisor-mode extensions and profile attributes (Ss*/Su*)
        "ssccptr", "sscofpmf", "sscounterenw", "ssnpm",
        "ssstateen", "ssstrict", "sstc",
        "sstvala", "sstvecd", "ssu64xl", "supm",
        // Page-table / virtual-memory features (Sv*)
        "svade", "svbare", "svinval", "svnapot", "svpbmt",
    };
}

static std::vector<StringRef> getPrivilegedFeatureNamesLoongArch64() {
    return {
        // Virtualization & Binary Translation privileged extensions
        "lvz", "lbt",
        // Atomic memory instructions requiring privileged access
        "lam-bh", "lamcas", "scq"
    };
}

static FeatureBitset computePrivilegedMask(
        StringRef Arch, ArrayRef<SubtargetFeatureKV> Features) {
    std::vector<StringRef> Names;
    if (Arch == "x86_64" || Arch == "i686")
        Names = getPrivilegedFeatureNamesX86();
    else if (Arch == "aarch64")
        Names = getPrivilegedFeatureNamesAArch64();
    else if (Arch == "riscv64")
        Names = getPrivilegedFeatureNamesRISCV();
    else if (Arch == "loongarch64")
        Names = getPrivilegedFeatureNamesLoongArch64();

    FeatureBitset Mask;
    for (StringRef Name : Names) {
        bool Found = false;
        for (const auto &F : Features) {
            if (F.Key == Name) {
                Mask.set(F.Value);
                Found = true;
                break;
            }
        }
        if (!Found) {
            errs() << "error: privileged feature '" << Name
                   << "' is not in the LLVM feature table for " << Arch << "\n";
            std::abort();
        }
    }
    return Mask;
}

// Label any "umbrella" features (such as "armv8.3") with `is_featureset`, to
// signal to cpufeatures that the feature bit does not gate any dedicated HW
// functionality of its own.
//
// For a 'featureset' bit, all HW / codegen support is gated by other bits.

static std::vector<StringRef> getFeatureCollectionNamesAArch64() {
    // alias for "+aes,+sha2"
    std::vector<StringRef> Result = { "crypto" };
    // these are just aliases for "+sve2,+sve-aes" etc.
    Result.push_back("sve2-aes");
    Result.push_back("sve2-bitperm");
    Result.push_back("sve2-sha3");
    Result.push_back("sve2-sm4");
    return Result;
}

// Architecture-level "uarch" features (such as v8.4a).
//
// These are similar to featuresets, but they differ in two respects:
//   1. They are not exactly equivalent to their implied features since
//      they include optional features.
//   2. They effectively act as a tuning flag for codegen.
//
// We report these in LLVM feature strings, but image matching does not
// require that they are actually present (they are treated as tuning bits).
static std::vector<StringRef> getUArchFeatureNamesAArch64() {
    std::vector<StringRef> Result;
    for (const llvm::AArch64::ArchInfo *AI : llvm::AArch64::ArchInfos) {
        // ArchFeature is "+v8.1a" — strip leading "+".
        Result.push_back(AI->ArchFeature.drop_front());
    }
    return Result;
}

static std::vector<StringRef> getFeatureCollectionNamesRISCV() {
    // Spec-defined collections from the RISC-V ISA manual.
    return {
        "b",      // Bitmanip — collection of Zba+Zbb+Zbs.
        "zk",     // Standard scalar cryptography.
        "zkn",    // NIST Algorithm Suite.
        "zks",    // ShangMi Algorithm Suite.
        "zvkn",   // Vector crypto NIST.
        "zvknc",  // Vector crypto NIST + Zvbc.
        "zvkng",  // Vector crypto NIST + Zvkg.
        "zvks",   // Vector crypto ShangMi.
        "zvksc",  // Vector crypto ShangMi + Zvbc.
        "zvksg",  // Vector crypto ShangMi + Zvkg.
    };
}

static std::vector<StringRef> getFeatureCollectionNamesLoongArch64() {
    // No spec-defined feature collection aliases are currently defined upstream.
    return {};
}

static FeatureBitset computeMaskFromNames(
        StringRef Arch, ArrayRef<SubtargetFeatureKV> Features,
        ArrayRef<StringRef> Names, const char *Kind) {
    FeatureBitset Mask;
    for (StringRef Name : Names) {
        bool Found = false;
        for (const auto &F : Features) {
            if (F.Key == Name) {
                Mask.set(F.Value);
                Found = true;
                break;
            }
        }
        if (!Found) {
            errs() << "error: " << Kind << " '" << Name
                   << "' is not in the LLVM feature table for " << Arch << "\n";
            std::abort();
        }
    }
    return Mask;
}

static FeatureBitset computeFeatureFeatureSetMask(
        StringRef Arch, ArrayRef<SubtargetFeatureKV> Features) {
    std::vector<StringRef> Names;
    if (Arch == "aarch64")
        Names = getFeatureCollectionNamesAArch64();
    else if (Arch == "riscv64")
        Names = getFeatureCollectionNamesRISCV();
    else if (Arch == "loongarch64")
        Names = getFeatureCollectionNamesLoongArch64();
    // x86_64 and fallback: no collection features.
    return computeMaskFromNames(Arch, Features, Names, "feature collection");
}

static FeatureBitset computeUArchMask(
        StringRef Arch, ArrayRef<SubtargetFeatureKV> Features) {
    std::vector<StringRef> Names;
    if (Arch == "aarch64")
        Names = getUArchFeatureNamesAArch64();
    // x86_64, riscv64, fallback: no uarch features yet.
    return computeMaskFromNames(Arch, Features, Names, "uarch feature");
}

static void emitFeatureTable(raw_ostream &OS,
                              StringRef Arch,
                              ArrayRef<SubtargetFeatureKV> Features,
                              ArrayRef<SubtargetSubTypeKV> CPUs,
                              unsigned NumWords) {
    FeatureBitset FeatureSetMask = computeFeatureFeatureSetMask(Arch, Features);
    FeatureBitset UArchMask = computeUArchMask(Arch, Features);
    FeatureBitset HWMask = computeHWMask(Features, CPUs, FeatureSetMask, UArchMask);
    FeatureBitset PrivilegedMask = computePrivilegedMask(Arch, Features);

    OS << "// Feature table: name, description, bit index, is_hw, is_featureset,\n";
    OS << "// is_uarch, is_privileged, implied features.\n";
    OS << "typedef struct {\n";
    OS << "    const char *name;\n";
    OS << "    const char *desc;\n";
    OS << "    unsigned bit;                // feature bit index\n";
    OS << "    unsigned char is_hw;         // 1 = hardware feature, 0 = tuning/mode hint\n";
    OS << "    unsigned char is_featureset; // 1 = architecture-level umbrella (v8.1a, RISC-V B)\n";
    OS << "    unsigned char is_uarch;      // 1 = architecture-level uarch hint (v8.1a, v9.2a)\n";
    OS << "    unsigned char is_privileged; // 1 = EL2/EL3/ring-0 only, no user-space codegen\n";
    OS << "    FeatureBits implies;         // transitively implied features\n";
    OS << "} FeatureEntry;\n\n";

    // Exclude features that shouldn't affect sysimage target matching.
    // Uppercase names are system register features (aarch64).
    // The blacklist covers tuning hints and privileged instructions that
    // differ between Intel/AMD but don't affect user-space codegen.
    static const char *blacklist[] = {
        // x86: tuning hints
        "ermsb", "fsrm",   // tuning hints (REP MOVS speed)
        "nopl",            // baseline assumption, not CPUID-detectable
        // aarch64:
        // speculative execution mitigation, not codegen-relevant.
        "ssbs", "ssbs2", "predres", "specrestrict", "specres", "specres2",
        // behaves as NOP if unsupported by CPU (HINT / backwards-compatible)
        "pauth", "bti", "clrbhb", "chk", "pauth-lr", "pcdphint",
        // inline assembly only
        "lor", "ras",
        // incorrectly categorized as a feature in LLVM 21
        // fixed in https://github.com/llvm/llvm-project/pull/152156)
        "use-fixed-over-scalable-if-equal-cost",
        nullptr
    };
    for (const auto &F : Features) {
        if (F.Key[0] && std::isupper(static_cast<unsigned char>(F.Key[0])))
            HWMask.reset(F.Value);
        for (const char **bl = blacklist; *bl; bl++) {
            if (StringRef(F.Key) == *bl) {
                HWMask.reset(F.Value);
                break;
            }
        }
    }

    OS << "static const FeatureEntry feature_table[] = {\n";
    for (const auto &F : Features) {
        bool IsHW = HWMask.test(F.Value);
        bool IsCollection = FeatureSetMask.test(F.Value);
        bool IsUArch = UArchMask.test(F.Value);
        bool IsPrivileged = PrivilegedMask.test(F.Value);
        OS << "    { \"" << F.Key << "\", \"";
        StringRef Desc(F.Desc);
        for (char C : Desc) {
            if (C == '"') OS << "\\\"";
            else if (C == '\\') OS << "\\\\";
            else OS << C;
        }
        OS << "\", " << F.Value
           << ", " << (IsHW ? "1" : "0")
           << ", " << (IsCollection ? "1" : "0")
           << ", " << (IsUArch ? "1" : "0")
           << ", " << (IsPrivileged ? "1" : "0")
           << ", ";
        emitFeatureBits(OS, F.Implies.getAsBitset(), NumWords);
        OS << " },\n";
    }
    OS << "};\n\n";
    OS << "static const unsigned num_features = "
       << Features.size() << ";\n\n";

    // Emit precomputed hardware feature mask
    OS << "// Precomputed mask of hardware (CPUID-detectable) features\n";
    OS << "static const FeatureBits hw_feature_mask = ";
    emitFeatureBits(OS, HWMask, NumWords);
    OS << ";\n\n";

    // Emit precomputed LLVM feature mask: HW (non-privileged) + uarch hints
    FeatureBitset LLVMMask = (HWMask & ~PrivilegedMask) | UArchMask;
    OS << "// Codegen-relevant bits: HW features + uarch hints, non-privileged.\n";
    OS << "static const FeatureBits llvm_feature_mask = ";
    emitFeatureBits(OS, LLVMMask, NumWords);
    OS << ";\n\n";

    // Emit precomputed uarch feature mask
    OS << "// Mask of architecture-level uarch features (e.g. v8.4a). Included\n";
    OS << "// in the LLVM feature string but ignored for target matching.\n";
    OS << "static const FeatureBits uarch_feature_mask = ";
    emitFeatureBits(OS, UArchMask, NumWords);
    OS << ";\n\n";
}

static void emitCPUTable(raw_ostream &OS,
                          const Triple &TT,
                          ArrayRef<SubtargetSubTypeKV> CPUs,
                          ArrayRef<SubtargetFeatureKV> Features,
                          unsigned NumWords) {
    OS << "// CPU table: name, base features (from Implies), full resolved features\n";
    OS << "typedef struct {\n";
    OS << "    const char *name;\n";
    OS << "    FeatureBits implies;       // direct feature bits from TableGen\n";
    OS << "    FeatureBits tune_implies;  // tuning feature bits\n";
    OS << "    FeatureBits features;      // fully resolved features (transitive closure)\n";
    OS << "} CPUEntry;\n\n";

    OS << "static const CPUEntry cpu_table[] = {\n";
    for (const auto &CPU : CPUs) {
        // Get the fully resolved features for this CPU
        FeatureBitset Resolved = getFeaturesForCPU(TT, CPU.Key);

        OS << "    { \"" << CPU.Key << "\",\n";
        OS << "      ";
        emitFeatureBits(OS, CPU.Implies.getAsBitset(), NumWords);
        OS << ",\n      ";
        emitFeatureBits(OS, CPU.TuneImplies.getAsBitset(), NumWords);
        OS << ",\n      ";
        emitFeatureBits(OS, Resolved, NumWords);
        OS << " },\n";
    }
    OS << "};\n\n";
    OS << "static const unsigned num_cpus = "
       << CPUs.size() << ";\n\n";
}

// Emit a feature enum for convenient access
static void emitFeatureEnum(raw_ostream &OS,
                             ArrayRef<SubtargetFeatureKV> Features) {
    OS << "// Feature bit indices\n";
    OS << "enum FeatureIndex {\n";
    for (const auto &F : Features) {
        // Create a C-safe identifier from the feature name
        std::string Name = "FEAT_";
        for (char C : StringRef(F.Key)) {
            if (C == '-' || C == '.') Name += '_';
            else Name += toupper(C);
        }
        OS << "    " << Name << " = " << F.Value << ",\n";
    }
    OS << "};\n\n";
}

// Emit a lookup function
static void emitLookupFunctions(raw_ostream &OS) {
    OS << "// Binary search for a feature by name (table is sorted)\n";
    OS << "CPUFEATURES_UNUSED static const FeatureEntry *find_feature(const char *name) {\n";
    OS << "    int lo = 0, hi = (int)num_features - 1;\n";
    OS << "    while (lo <= hi) {\n";
    OS << "        int mid = (lo + hi) / 2;\n";
    OS << "        int cmp = strcmp(feature_table[mid].name, name);\n";
    OS << "        if (cmp == 0) return &feature_table[mid];\n";
    OS << "        if (cmp < 0) lo = mid + 1;\n";
    OS << "        else hi = mid - 1;\n";
    OS << "    }\n";
    OS << "    return NULL;\n";
    OS << "}\n\n";

    OS << "// Binary search for a CPU by name (table is sorted)\n";
    OS << "// Use find_cpu() instead — this is the raw lookup without alias resolution.\n";
    OS << "CPUFEATURES_UNUSED static const CPUEntry *_find_cpu_exact(const char *name) {\n";
    OS << "    int lo = 0, hi = (int)num_cpus - 1;\n";
    OS << "    while (lo <= hi) {\n";
    OS << "        int mid = (lo + hi) / 2;\n";
    OS << "        int cmp = strcmp(cpu_table[mid].name, name);\n";
    OS << "        if (cmp == 0) return &cpu_table[mid];\n";
    OS << "        if (cmp < 0) lo = mid + 1;\n";
    OS << "        else hi = mid - 1;\n";
    OS << "    }\n";
    OS << "    return NULL;\n";
    OS << "}\n\n";

    OS << "// Expand implied features transitively\n";
    OS << "// Transitive closure of \"For all features added, add anything they require them.\".\n";
    OS << "CPUFEATURES_UNUSED static void _expand_entailed_enable_bits(FeatureBits *bits) {\n";
    OS << "    int changed = 1;\n";
    OS << "    while (changed) {\n";
    OS << "        changed = 0;\n";
    OS << "        for (unsigned i = 0; i < num_features; i++) {\n";
    OS << "            if (feature_test(bits, feature_table[i].bit)) {\n";
    OS << "                FeatureBits old = *bits;\n";
    OS << "                feature_or(bits, &feature_table[i].implies);\n";
    OS << "                if (!feature_equal(bits, &old)) changed = 1;\n";
    OS << "            }\n";
    OS << "        }\n";
    OS << "    }\n";
    OS << "}\n\n";

    OS << "// Expand implied non-features transitively\n";
    OS << "// Transitive closure of \"For all features removed, remove anything that requires them.\".\n";
    OS << "CPUFEATURES_UNUSED static void _expand_entailed_disable_bits(FeatureBits *bits) {\n";
    OS << "    int changed = 1;\n";
    OS << "    while (changed) {\n";
    OS << "        changed = 0;\n";
    OS << "        for (unsigned i = 0; i < num_features; i++) {\n";
    OS << "            if (feature_test(bits, feature_table[i].bit)) continue;\n";
    OS << "            if (feature_intersects(&feature_table[i].implies, bits)) {\n";
    OS << "                feature_set(bits, feature_table[i].bit);\n";
    OS << "                changed = 1;\n";
    OS << "            }\n";
    OS << "        }\n";
    OS << "    }\n";
    OS << "}\n\n";
}

int main(int argc, char **argv) {
    InitLLVM X(argc, argv);

    LLVMInitializeX86TargetInfo();
    LLVMInitializeX86TargetMC();
    LLVMInitializeAArch64TargetInfo();
    LLVMInitializeAArch64TargetMC();
    LLVMInitializeRISCVTargetInfo();
    LLVMInitializeRISCVTargetMC();
    LLVMInitializeLoongArchTargetInfo();
    LLVMInitializeLoongArchTargetMC();

    if (argc < 2) {
        errs() << "Usage: " << argv[0] << " <triple>\n";
        errs() << "  e.g.: " << argv[0] << " x86_64-unknown-linux-gnu\n";
        return 1;
    }

    Triple TT(Triple::normalize(argv[1]));
    std::string Arch = TT.getArchName().str();

    auto STI = getSTI(TT);
    if (!STI) return 1;

    auto Features = STI->getAllProcessorFeatures();
    auto CPUs = STI->getAllProcessorDescriptions();

    // Determine number of 64-bit words needed for feature bitset
    unsigned MaxBit = 0;
    for (const auto &F : Features)
        MaxBit = std::max(MaxBit, F.Value);
    unsigned NumWords = (MaxBit / 64) + 1;

    raw_fd_ostream &OS = outs();

    emitHeader(OS, Arch);
    OS << "#include <string.h>\n\n";
    OS << "// Generated for triple: " << TT.str() << "\n";
    OS << "// " << Features.size() << " features, " << CPUs.size() << " CPUs\n\n";
    OS << "namespace tp {\n\n";

    emitBitsetType(OS, NumWords);
    emitFeatureEnum(OS, Features);
    emitFeatureTable(OS, Arch, Features, CPUs, NumWords);
    emitCPUTable(OS, TT, CPUs, Features, NumWords);
    emitLookupFunctions(OS);
    OS << "} // namespace tp\n\n";
    emitFooter(OS, Arch);

    return 0;
}
